apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  annotations:
    # <K8S_ROLE_MAPPING>: "arn:aws:iam::<CLOUD_ACCOUNT>:role/<CLUSTER_NAME>-<WL_NAME>-backend-dev-role"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-tenant
  annotations:
    # <K8S_ROLE_MAPPING>: "arn:aws:iam::<CLOUD_ACCOUNT>:role/<CLUSTER_NAME>-<WL_NAME>-backend-dev-role"
