---
# Business settings that will be promoted between environments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "api"
spec:
  template:
    spec:
      containers:
      - name: "api-container"
        env: []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "api-tenant"
spec:
  template:
    spec:
      containers:
      - name: "api-tenant-container"
        env: []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "web-client"
spec:
  template:
    spec:
      containers:
      - name: "web-client-container"
        env: []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "web-tenant-admin"
spec:
  template:
    spec:
      containers:
      - name: "web-tenant-admin-container"
        env: []