---
apiVersion: batch/v1
kind: Job
metadata:
  name: api-migration
spec:
  template:
    spec:
      containers:
      - name: api-migration
        command: ["yarn", "dbmigrate"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: api-tenant-migration
spec:
  template:
    spec:
      containers:
      - name: api-tenant-migration
        command: ["yarn", "dbmigrate"]