---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: web-client-keda
spec:
  advanced:
    # scale back to original replicas count after the ScaledObject is deleted
    restoreToOriginalReplicaCount: true
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-client
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        metricName: nginx_service_requests_total
        threshold: "500"
        # scale based on per-second rate of requests measured over last 1 minute
        query: sum(rate(nginx_ingress_controller_requests{host="web-client.<WL_NAME>.<DOMAIN_NAME>", ingress="web-client", exported_service="web-client"}[1m]))
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: api-keda
spec:
  advanced:
    # scale back to original replicas count after the ScaledObject is deleted
    restoreToOriginalReplicaCount: true
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  pollingInterval: 30
  cooldownPeriod: 150
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        metricName: nginx_service_requests_total
        threshold: "500"
        # scale based on per-second rate of requests measured over last 1 minute
        query: sum(rate(nginx_ingress_controller_requests{host="web-client.<WL_NAME>.<DOMAIN_NAME>", ingress="api", exported_service="api"}[1m]))
