---
# Workload versions (image + image tag)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "api"
spec:
  template:
    spec:
      containers:
      - name: "api-container"
        image: "<REGISTRY_URL>/<WL_NAME>/api:0.1.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "api-tenant"
spec:
  template:
    spec:
      containers:
      - name: "api-tenant-container"
        image: "<REGISTRY_URL>/<WL_NAME>/api-tenant:0.1.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "web-client"
spec:
  template:
    spec:
      containers:
      - name: "web-client-container"
        image: "<REGISTRY_URL>/<WL_NAME>/web-client:0.1.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "web-tenant-admin"
spec:
  template:
    spec:
      containers:
      - name: "web-tenant-admin-container"
        image: "<REGISTRY_URL>/<WL_NAME>/web-tenant-admin:0.1.0"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: api-migration
spec:
  template:
    spec:
      containers:
      - name: api-migration
        image: "<REGISTRY_URL>/<WL_NAME>/api:0.1.0"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: api-tenant-migration
spec:
  template:
    spec:
      containers:
      - name: api-tenant-migration
        image: "<REGISTRY_URL>/<WL_NAME>/api-tenant:0.1.0"