---
# Defines common characteristics between environments
# Kubernetes specific settings, eg resource limits, health checks, persistent volumes, affinity rules, etc.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "api"
spec:
  template:
    spec:
      containers:
      - name: "api-container"
        livenessProbe:
          httpGet:
            path: /livez
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 6
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 2
          failureThreshold: 6
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 100m
            memory: "256Mi"
          requests:
            cpu: 40m
            memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "api-tenant"
spec:
  template:
    spec:
      containers:
      - name: "api-tenant-container"
        livenessProbe:
          httpGet:
            path: /livez
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 6
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 2
          failureThreshold: 6
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 100m
            memory: "256Mi"
          requests:
            cpu: 40m
            memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "web-client"
spec:
  template:
    spec:
      containers:
      - name: "web-client-container"
        livenessProbe:
          httpGet:
            path: /livez
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 6
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 2
          failureThreshold: 6
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 100m
            memory: "256Mi"
          requests:
            cpu: 40m
            memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "web-tenant-admin"
spec:
  template:
    spec:
      containers:
      - name: "web-tenant-admin-container"
        livenessProbe:
          httpGet:
            path: /livez
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 6
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 2
          failureThreshold: 6
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 100m
            memory: "256Mi"
          requests:
            cpu: 40m
            memory: "128Mi"