apiVersion: v1
kind: Service
metadata:
  name: api
  labels: {
    expose-metrics: 'true'
    }
spec:
  type: ClusterIP
  selector:
    "cg-devx.metadata.service": "<WL_NAME>-api"
  ports:
    - protocol: TCP
      port: 3000
      targetPort: http
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: api-tenant
  labels: {
    expose-metrics: 'true'
    }
spec:
  type: ClusterIP
  selector:
    "cg-devx.metadata.service": "<WL_NAME>-api-tenant"
  ports:
    - protocol: TCP
      port: 3000
      targetPort: http
      name: http

---
apiVersion: v1
kind: Service
metadata:
  name: web-client
  labels: {
    expose-metrics: 'true'
    }
spec:
  type: ClusterIP
  selector:
    "cg-devx.metadata.service": "<WL_NAME>-web-client"
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http

---
apiVersion: v1
kind: Service
metadata:
  name: web-tenant-admin
  labels: {
    expose-metrics: 'true'
    }
spec:
  type: ClusterIP
  selector:
    "cg-devx.metadata.service": "<WL_NAME>-web-tenant-admin"
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
