---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "api"
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  target:
    name: "api"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-workloads-secret
  refreshInterval: "10s"
  dataFrom:
    - extract:
        key: /<WL_NAME>/sta/api
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "api-tenant"
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  target:
    name: "api-tenant"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-workloads-secret
  refreshInterval: "10s"
  dataFrom:
    - extract:
        key: /<WL_NAME>/sta/api-tenant
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "web-client"
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  target:
    name: "web-client"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-workloads-secret
  refreshInterval: "10s"
  dataFrom:
    - extract:
        key: /<WL_NAME>/sta/web-client
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "web-tenant-admin"
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  target:
    name: "web-tenant-admin"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-workloads-secret
  refreshInterval: "10s"
  dataFrom:
    - extract:
        key: /<WL_NAME>/sta/web-tenant-admin
